services:
  app:
    image: ghcr.io/sitepilot/php-nginx:${STACK_PHP_VERSION:-8.3}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:?}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:?}.rule=HostRegexp(`${COMPOSE_PROJECT_NAME:?}.{any:.+}`)"
    environment:
      NGINX_PUBLIC_DIR: 'public'
    volumes:
      - './files:/app/files'
    networks:
      - default
      - stack

  redis:
    image: redis:7
    volumes:
      - redis:/data

volumes:
  redis:

networks:
  stack:
    external: true
